name: Update Resume Gist

on: push

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.TOKEN }}
        gist_id: c29df8727b2ea5b1ccff7606ed547b97
        file_path: resume.json
